language: java
jdk:
  - oraclejdk8
script: "mvn clean test -B"
deploy:
  provider: releases
  user: "PiotrTrelinski"
  password: "Bonufacy69"
  file_glob: true
  skip_cleanup: true
  on:
    tags: false
